name: Hands-On Practice

on: 
   push:
     paths:
        - 'src/**' # The trigger: runs every time you push code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo "Starting the practice session..."
          echo "The runner is ready."
          
      - name: Show the environment
        run: env
      - name: This step will fail
        run: |
          echo "I am about to run a fake command..."

      - name: Try to print the secret
        env:
          MY_KEY: ${{ secrets.MY_SUPER_SECRET_KEY }}
        run: |
          echo "I am going to try and print the secret below:"
          echo "The secret key is: $MY_KEY"
          echo "Notice how GitHub masks it with asterisks!"
        